### ISSUE TITLE
etiuSrewoPreganamX版本问题

### ISSUE THREAD

**Issue by sino1641** [xcanwin/Win-Software-Crack#18]
请问一定是每个版本都需要适配不同的破解吗 
还是一定要用作者提供的安装包？
我直接官网下的最新安装包 0030
执行bat之后还是提示未激活

**Comment by xcanwin** [comment]
对，都需要下载特定版本的。注册机容易误报存在病毒。不喜欢以各种理由要求用户关闭杀毒软件的行为。
