### ISSUE TITLE
XmanagerPowerSuite-7.0.0007.exe无法安装

### ISSUE THREAD

**Issue by wengzuyang** [xcanwin/Win-Software-Crack#6]
XmanagerPowerSuite-7.0.0007.exe安装时提示
![image](https://user-images.githubusercontent.com/11473283/129470364-6976bb90-608f-4b56-b6eb-d35fec3bce75.png)
能否提供一下可用的安装文件

**Comment by xcanwin** [comment]
安装前把电脑年份改成2018年，安装后恢复年份

**Comment by wengzuyang** [comment]
果然可以，谢谢
